# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-09 04:02
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artapp', '0003_auto_20180705_0200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='art',
            options={'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.AlterModelOptions(
            name='arttag',
            options={'verbose_name': '分类标签', 'verbose_name_plural': '分类标签'},
        ),
        migrations.AlterField(
            model_name='art',
            name='summary',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='概述'),
        ),
        migrations.AlterField(
            model_name='art',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artapp.ArtTag', verbose_name='分类'),
        ),
    ]
